---
title: "plot group average correlation matrix"
output:
  pdf_document:
    toc: yes
    toc_depth: 3
  html_document:
    df_print: paged
    toc: yes
  html_notebook:
    df_print: paged
    toc: yes
---

```{r}
setwd("~/Documents/oleary/rest/figure/")

library(ggplot2)
library(reshape2)
library(viridis)
library(tkmisc)
library(RColorBrewer)
library(gridExtra)

```


```{r}
fcon_matrixa <- read.table("groupavg.txt", header = F)
a <- as.matrix(fcon_matrixa)
#a[upper.tri(a)] <- NA
xf <- melt(a)
```


```{r}
groupavg <- ggplot(xf, aes(x=Var2, y=Var1, fill=value))+
  theme_minimal() +
  scale_y_reverse() +
  coord_equal(expand=FALSE) +
  scale_fill_gradientn(colors = colorRamps::matlab.like(100), na.value = "transparent", limits = c(-0.8,0.8)) +
  geom_raster() +
  theme(axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(), panel.grid = element_blank()) 

rowsep=c(5,37,42,61,73,121,126,160,184,193,202,215,219,222,238,250,267)
for (i in 1:length(rowsep)) {
  groupavg <- groupavg +
    annotate("segment", x=-Inf, xend=rowsep[i], y=rowsep[i], yend=rowsep[i]) +
    annotate("segment", x=rowsep[i], xend=rowsep[i], y=rowsep[i], yend=Inf) +
    annotate("segment", x=Inf, xend=rowsep[i], y=rowsep[i], yend=rowsep[i]) +
    annotate("segment", x=rowsep[i], xend=rowsep[i], y=rowsep[i], yend=-Inf) }

groupavg

#Save off the image (three plots combined
#png('groupmatrix.png',units="px",res=300,width=3500,height=1000)
#grid.arrange(groupavg, groupavg2, groupavg3, ncol=3)
#dev.off()
```

```{r}
blowup <- melt(as.matrix(fcon_matrixa[215:267,1:267]))

blowupplot <- ggplot(blowup, aes(x=Var2, y=Var1, fill=value))+
  theme_minimal() +
  scale_y_reverse() +
  coord_equal(expand=FALSE) +
  scale_fill_gradientn(colors = colorRamps::matlab.like(100), na.value = "transparent", limits = c(-0.8,0.8)) +
  geom_raster() +
  theme(axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(), panel.grid = element_blank()) 

rowsep=c(5,37,42,61,73,121,126,160,184,193,202,215,219,222,238,250,267)
for (i in 1:length(rowsep)) {
  blowupplot <- blowupplot +
    annotate("segment", x=-Inf, xend=rowsep[i], y=rowsep[i], yend=rowsep[i]) +
    annotate("segment", x=rowsep[i], xend=rowsep[i], y=rowsep[i], yend=Inf) +
    annotate("segment", x=Inf, xend=rowsep[i], y=rowsep[i], yend=rowsep[i]) +
    annotate("segment", x=rowsep[i], xend=rowsep[i], y=rowsep[i], yend=-Inf) }

blowupplot
```



